apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: apple-wallet-certificate-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgBVxf2dkVJff4LOg6Y0lZFKTTfyWH8PT4eESXNufW/FhOR4bxTgD/ynX+bFpyc0z1d7/V1/IT9dHpAIcl8bIPLRqEMwGSB1LFhrkiQKfDEJPwwk0MbfBV4F+XNfvLwnzs2aMA15hdeaUhexqs+25GYXwi/Vr9CaZDt39e1DUnaIMg7zvYAPTknBqC2nyY5BB32eKYNT52ophPXnH+MotoRmtn8qdbFytneXUwBpjnyLMRCzZ4gw5mAnsoXVEfHo67BkJGQeelno4276ZxFgyFNAuGeZA+IdouUcCsvEQPCJDOSUG/qI9JCUoY4qbZyRBX2dJZG8IHzsALa8SbQvmqtxy1s8l6wW0lm9LJ4HloseiT5kk2G2Nd9CV+ziGnMRxlHm69XychaalT4/p0pSmuaa2FgwAfGrsl41zT/0u8QXCDhGj+6oPsd+3+SSqCss4XDAYqvob22w1jNsKo6ZEqwVTgp/TTgP7xsQpRbgz/SXvAKiyIAXXpvLEMg3f9xpDXeN7TDLJKPedHJNgYgwrYY//SPmGH0c6ryUnDfVbDmLQCXGogcVN8KhSKziyowFr7mko7msvYl/y2KcY8Ug9eWo7XgsOAeRWT1vKNGi4HCqjWZ+QovvhVGtiu6rWRFbMOLq9ywG6QHItsBewpVMBJYjhbktiHRTHY6tCMGekvBMKuxmqXJrELVuqARqIAtnpSxBJaAZwp4D46O2EU7Q/WGC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: apple-wallet-certificate-secret
      namespace: ${NAMESPACE}

