apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgCOROG6a9xkZzZiVB7MeHThZAJoioBkqihdP4qg9X99e9ntkkm5pkIoTeuN4fdI8x42fYacJCiz33IZWLzk0MzwvJXs3ueqIhD4/oWkrSclNvO35lfw0hrRm6jC9/H7VophD9Ifs3VXCifu9ooKS2Q6FgJ2grEMKQoRipkXYhrRUq3Kzk9MEoHyf43WZHDyJyXwbX/eWDsEybiLUxUJWdeug0odsZWYbIt5HPeGNAVyzsKZLUR3O1WXXrkWFnsChTClEDAXPwszkdORqBXXDGYQBQqHBmypxfCGClPtxPpDHbo8HEiqAdi3gQhpDDp59wyUZfGuzGy31Q/Ne7U2UF8xHwOXDrDlBZzCKkKDbF1dwM7arGxwp3vAb2G+7tHFEC3tNU9HMTJ8bc1/mS2nTBKvRR7p5aH95g6U2kVIDN4SOoDlP5NTSgD3K1XIEMEMsA0TjdAsRlSNUOqVU6bYga8EKebrPPkxcqMRFxPQIoH8KFUac341VcG+KTbRoo/uDwNYPTZRx8W5Fyt13OrVerT9NCihjMbCUInU3EJC498dJpZF6ZY4rSMM5vO5rPTMQWlsQwv4EJc13wqbnFjOcDbjbi+xHzY+fdH7dnG0y2+WoM16kZDr4QXuKIxKr7iewLNTZL7Mlx/WV9qbmw4pfsx4QyGrRabyPW5xbWYHe8jcDwRPbSQT7dYk+aOdP0pz2Nrm7gJwqU/yErBvmg9s9We/ZxIj3rR+creLazHkWQaJr7ufapn4PNp66l7MZg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
      namespace: ${NAMESPACE}
