apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgAsnMCQbPRG24cXZBS5F6LsqqoAq0b3aTICR+49OV6Rpmm6WQp+LEj90joWjERXIdT4WOSXLxqrowPDWLHjNhk8GlAeYGIV8NGxb+zpft5bXbf+I3sniqzid5QSBTXLzHaFCpIDeKPck0871gjd2Ph9RZU/bAE8H/RXG5FIp496RWPP+ilXxlubI1IkfD3ejPEkMLhPoQCItHLmU/us1C4YQaWKu7MN1szVHKzGVRLyAysqBMnn5C2w8LmXVMLD7O7xqb179pHcmtSUZ2ePhBotoMJWDYrxjHLH18QhQp0OLFgwG8AmA9l/u6zOAhDoQVCLygjFvpq4zuc2ugQefgEuDMGe21504SrE17EUYATJ6ZYG5vVXM3mnABmOtcnE2zvXxaePyB7qX8RKoGWVyk1mB5fKjoRBEsWUyCAXscvEwlNagEHY1O8RjTtvMVHYZ8B0zU2yheqV2Ma/nRrt/tWspIEjwNpVHzhRwt+UBW58sjTSONN/btymGWJfda9LZXdnsUQWSMTWIJMR+qNstIjkChrks7Eh5OScRVTtHzGxS3Ovcg/ocy6tvujxqvqF6gS8aOg2Xcx2fGbxviQ9fxMtvdjqofVzU0wbfqcAVwYIWuW/MHHcLONt+8RcyeJPBgb0ToODMuvUuqeyafJUiQ6Yoa6viu6EwzPGXKct3th8zUcNDP1AbmsgNOT76sCjeH39bFbjtWM4cnALpKhp92hdzZF6lFpoCckNBSz3iv59jA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
      namespace: ${NAMESPACE}
