apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kupaliska-starz-be-minio
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgA03nWWXLkEUnfca61VHFajDTcYI/rrz2AS0EnBVbhTpyy4yvG6dNY6AT8C8N5PM/d2dsYk2oHIIdaNe3dfqavkRFHmMd5A2QoaLGzYHUeFgLD92+LTnBUAh9SP+3IvXiRiHhLR5ZoscxbrwehCFLtWzkNZfvvOkC/CB9rInr6PpYgj+a7cAaiBF0vmmrixq/rTjvX8BXPQK2E6Y9sgpM/C4oK+1Fjw+ZlEymV1uZGY/YrLv/++XMYwEmigXdaP695+bptwQQF87R4QRd0bAwA1CPN3i9pXlKp5t9XTL++VyMJyJ9eFx6wi/RjBOxMa0CxEkAkM3PFJZJGwAh/HmJET58Xl4BIQ7R3ZUFJOBzezuIarBZQPaLqJAA1dVltQ7pKYdo5346wK7WBn1jYL0Dhe/oPmra0ERIo6XEZr+AsdImcfnq1RO1ko9fyH1emi3kT4P9hyRrzU+euTpNks8HXN/UhoyONy6v50hRZa+dRJVdwUmwJzPX/13CQ0vZ/Higl3iEAnsTMYOV7Btm/7nKegtur8WbtEo7KLCjjjMX0aPZjXdSeFpHiYp0ksrZdpCXWdKOkD5ChWyaAezc2le3zFYcctCb8MZSaxaxNXTaFxRq2Jk1JPkCH4a20cxUnnUifz4mNe0xysH4IVXAsKk+ZxAyH4GlcHwLmBWaeC3mKKsVU9/UQNo7EHAwrgI6Ce15wrCFr8I1w9QBmT9YcPaWEJ
    MINIO_SECRET_KEY: AgA6nbKilbmBGahx2+GmEjGzUH0IrtMiz90hPPRcZFzdTzMsLaMfr2B8wu6VfQGYVGmkzwImvgx2LOf2Acb+xO94Cavibivqb5uoOucNaxLQhKhlY8BRRCiFODMnjaNgCuy1F8EBTn2vMIdOg7e0gbYGPoHdxb/ToN6SbqpldVnuo7is46TqQBKU5dxI/RNKUdSWkTQuFqMyDIrJrj2nsdjflDcfrVkc3ABE/fa2hicfn/Ig8RQqlZPfborNUmd5/f8oPZWhds26sa91kvte31NlAGwFQcxaI5akAGFN4s87frsLaesqscQaz1E7tWonXoGGCoH6JySP7/i5ZRo5vw3NIPBwCm2ShkLmMousnRbwV+mkh6HFK1HmGVK79pkYNjI8n2Z/1rlzfHjdtXLTFj6IzCnZuGr48YgTlzCY4jMUXkckMIBfRuIAEuslMaZBt5wS+coSth1dp1eG0DQHNhMaQEMD6HGZqBawO5hDLCbn6d1R3gVw+MXYRP2jWdO9v0mQ0ehx7vCmRe/ZC96BYd+1tc+TB+BxMQVU8j1mzGZIW+3FU0w3wEOMBkgD33wMeflAZTgPvlHTeUaHRu/18SrT1+RST5XrVJ2il25VQNiUZpRxfvqyiSYC4/wrNuvqAh249f6asACZWsjlakQ5HaguMGGE+unbYHt6yWN+uDIRhBNMirxjNMeUxfohQQmWgwFxUEMQ7J2tQ8Y/3tOIk1Ze+2KtnZvKPGnr+chzuRsPow==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: kupaliska-starz-be-minio
      namespace: ${NAMESPACE}
