apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: minio-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MINIO_SECRET_KEY: AgBGOJ7aO1OBJ8hKGb3/FUoyXPb5yekMlHrTmWSpy+rIKBIoOtj7grllmxmbUZWeGuqIcU9FewJbBhx9o2p+kVEn+0ZPePqyIbiVQ8laLRgybcaZD3DwYmFMTOHY+xFhkh8DGJqO+X/seoEUmewh2tg3DqSmVHri2G8VdTOGBKVo0NUdDXVyms6ZnB9UpoMPpfvDUELaFaWnNTMHBXQsRoxmDeul7T6IgJQ6xf3CtVHi9yai5UMUv0zqYBjFN/+GJ2LphqdjmzbwSYzKTEW7S3FAF+bsbgMhWKlzDjlOgj6V+BpZNyFO9wZSx//4zaM1Q9uYd221ECh9Hc2WydG9fJ17xvnCEFiuqo2M6qRbaa0AbNMsKpyPWRksgPgX0Jk9UV4zeJ5PM/rEx8WE6mMb2ZKZE+ioAMA8RMR/Hn8UchvZloaHHcFOfeGLT7kwb2EPJH+keN2iesNnax/26ZRDCf07SY9azEV2n3VxGc4xACLmVBZeQjCJGz9HqPNMw7vl35ZazovuIEjM06vf5QNKrW5XjiLLiDwDzwlIaZesB/UDjJ7ytYemLt3CkFVKmlwa0gH+NYuvSN+dxbTJKsq/5qR1B44bLkQe8hyMVbgGICk2Dmz/Scw+QOsXfl2mcIASNY3wbOQRjahQYhVvBmp9JhCEO/ninDNBLbqM8BTJ2KmMi29GBF6Im98OMpcNz/UoI+b9VsVs/5s7kv3H6KaQRec=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: minio-secret
      namespace: ${NAMESPACE}
