---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-password-pepper-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    PASSWORD_PEPPER_CURRENT: AgA0KZHtyidHRL6FuZPA8gtG8f1b6bcu4CinxyNOWSR5FD3AFQ+jANYtA3qNg8T5kEf5mSlaXNopeb4CqLQkql0Yn475QOSsWCgPtCHJNYHV5/48MwQq0ujs2Fzl+5xKJr0xXYGcwosSTo8dhgmSw1ENJ5xPBWOVX513yevzXB+8qmoSqoZCOHRLsFb43KmaT4Xq02MYBVC768ZQF4vTKQKBp83npFSrvQK3ogovasBrmQrjSLOpn7nik59CiHLD3JXCpG986QyJjzYDdN9bfrExCdEw/PUylPJ7Ey9llmkCJ+1crhUgUWiRMUpEWmDt22jVvdf94cukEBlA93dhL+2ChLmsySH4mO8LrYoU35VGeRcQ8XMTb7NiQg6r9xFKogPNW491UqN1KIfaaZvXIkMe/GR47ZhmgQq2I1EzSqSI7Jv+bILs62aVozKKP5sI/b6akBtRdLU6ehkec6LZndwVFsZ3hf5lQXL/lCvucZT45rDOzmbfSr49qs3esYcCeR14OSY7PE5RRlEbyYWzboN/xrxy3Ax06FU4LT1TfEobeItbb8RH19xrfve2VO4R/vCy3ItuitcGmeGXxXNkWhFT8vmYkVWvriV5Cdkw/AeG/iYAh11wT4HYO534m/wbMkuiM+KbySC6beCtJHYJQIgI2qJ2XxVU5iYCwbWGwJ+/E7ypQjzgfO9ZnvFcLt8R41amymAV5nZQocgs2raMAmovCgZHZtDmZ3wglcK3FQpK1w==
    PASSWORD_PEPPER_PREVIOUS: AgA/QLLXRkJoXqEpUsV0vdsGbODhJysP8F/xCJQelcySDuGTnrLUVfc5bD0Po/SynmJscv79yKnXmadCK9mK+if8OEf+DwzLcDSNbNgXHpbaKqXU26jH9QwwzRSeZcFTEr1Qm2SnuB3FhdOj5UpkXm/lgadSWz0vte9mCPNdsteChFJ1KcG2F1pJGVnL3mXJj7H24IZKK2/ANtNqddF+5xuNhTMAjumv8l6jeTRnIv6JYw14x8GTiqI2oLuFYLM7bQakOCpK2ZxTo7wDtds18V8W3yEyRS8GYTa1NH3gxVpxShUIgp8nVPNeXEgDr6KUYyB2Lqohpe2PakYyZDUfJqmkdFYxw9Y5rTLC/LQ4xm8nGVNkQpplQMZLVdPEuLgnihfr9KifXJMshhj1Ao0h0DvQnTDz95Sp5nL99/3eU2v8F72Eal1OCm3tWmAr9UzsP1JQcG39UEw1wrP4R0I9suXO/OmVN/DqfY5szTRQBe8g6HtvADwtcSu29yIA1dKWSe99aMlt2TAZ8Bxjkc9UktZf+ncQeKDfGDQJdgystxDUohErOcScu8iukBwC0obDN/oa2dspIBYMqKQxuJ8eyI/oqONPR5NUMwJBUkLSTN0k3Ivy2lqRrS5n1qtT71jVomVHQDuUhVsgqUABDdT7ISQnFGwDCIzkBoX/xW7mson7Wu7fJWA7wTsS3I+cbqDH2F/GQGnGspxscWpfyf7OItKR7k/rGTD8ZDchq0jloOtv+g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-password-pepper-secret
      namespace: ${NAMESPACE}
    type: Opaque
