FROM node:14-alpine as development

ENV NODE_ENV development
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci


FROM development as builder

COPY . .
RUN npm run apidoc:scan
RUN npm run build


FROM development

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]

COPY docker/start.sh /start.sh
RUN chmod +x /start.sh
CMD [ "/start.sh" ]

COPY .sequelizerc /app/.sequelizerc
COPY resources /app/resources
COPY files /app/files
COPY locales /app/locales
COPY --from=builder /app/apidoc /app/apidoc
COPY --from=builder /app/dist/config /app/config
COPY --from=builder /app/dist /app/dist

VOLUME ["/app/files", "/app/logs"]
