FROM node:14-alpine as development

RUN apk add --no-cache tini
WORKDIR /app
ENV NODE_ENV development

COPY package.json package-lock.json ./
RUN npm ci


FROM development as builder

COPY . .
RUN npm run apidoc:scan
RUN npm run build


FROM development as runtime

ADD https://raw.githubusercontent.com/eficode/wait-for/master/wait-for /wait-for
COPY docker/entrypoint.sh docker/start.sh docker/deploy.sh /
RUN chmod +x /entrypoint.sh /start.sh /deploy.sh /wait-for

COPY .sequelizerc /app/.sequelizerc
COPY resources /app/resources
COPY files /app/files
COPY locales /app/locales
COPY --from=builder /app/apidoc /app/apidoc
COPY --from=builder /app/dist/config /app/config
COPY --from=builder /app/dist /app/dist

VOLUME ["/app/files", "/app/logs"]

ENTRYPOINT [ "tini", "--", "/entrypoint.sh" ]
CMD [ "/start.sh" ]
