resources:
  - ../../base
  - secrets/app.secret.yml
  - scaler.yml
  - secrets/minio-secret.secret.yaml 
 
configMapGenerator:
  - name: env
    namespace: ${NAMESPACE}
    behavior: merge
    envs:
      - .env

generatorOptions:
    disableNameSuffixHash: false

configMapGenerator:
- name: env
  namespace: ${NAMESPACE}
  behavior: merge
  envs:
  - .env
