resources:
  - ../../base
  - secrets/app.secret.yml
  - scaler.yml
  - secrets/minio.secret.yml
  - secrets/keys.secret.yml
  - secrets/test-keys.secret.yml
  - secrets/apple-wallet.secret.yml
  - secrets/google-wallet.secret.yml

generatorOptions:
    disableNameSuffixHash: false

configMapGenerator:
- name: env
  namespace: ${NAMESPACE}
  behavior: merge
  envs:
    - .env
