apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgB+k9FaMcvrzy6LdVLa/SOwrB4zPasVugHPSn5GqiMmPFomE+gGUWpiSLMiivqqvH8vDEME6L4i/DSedzOGpFsgvRUyJqG4N/8Af3PvNOhRZoQUapHfcF7a7EkOPnrI12AczxOJalrspcXl1tjUE08FmtdTzi+e7uEl85cUgFxeC+zq9m6kWLXhJMj6VZw5/p8KFYhZ0CDxw415FNA8kS2sB6OOoGJTA0EQ0/IZ8GL2Ru7Y20h0pENAWbrV1HSq0XALL4haV7ToYF01n5BhGaK6JatYTcb3wqFm470nY2GH7L8j6Ow10VkQ5vViIhgUijuyt3Ytbsq66Dn4dI6qoKyUtzNHK/7/YTio6WuvPsyF5h0owzGcRji+0v9LUYn0jYAhUWuDsf5kV2FZdGUAsy1FLiesIiQjXOi1qXXAY2mGZyCFrC7rQ+mqPzIcswQEYqo527Mp6WLsxHE1SXW+sPD6SH6drbiA0rtvqbqCKE2x7q/v8Y2+EkZmRyC0arZqxLkpMalqc4GXLqLCn/pK08hQZKKEVvEVu3NAbSmLBbeib8RDP0iXzV2vMptTvBi1q52i6z9tji8gUtaYM6ixdaMoGWw0cdeZgb8/1SUYljXmrLDZbIJD0QFb2/OXKZ/mgrehl8v/kDTaKBzbf54RGXvpVCeJpN7tVdOGWNMXn9M9p/tKJT4p5l4C/HIj0AfR66k/k6VNjPSalSBOnvcTYYerpKF07w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
      namespace: ${NAMESPACE}

