apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgBTpUuY9kWyVbnjRX9TSUSlEh7Xek78Coqh+4tLra9pR3Q1nBh3zNiDmwKJaZbcEEbKXn/y/SKa9dZzQkiMsnXVJzUz7gZrVfXr149Y2jOzw5Qg3ATxqDqOitxX2ZmJptRELwdCMbW4K6brwJctcEmfnbDdoxzuv9T6z/fBfpcxm/XdvFyJ27KDX3M8lNGvO4iIBlwubgbYTkSyJjKuaTynEtH1PKMKmQbes8q8LgTGLCRz2VFBCdZ5uEAobiU2llyEBAwqV86FMOVm93UqDbpaEu38h/bQeGTLSw6MonREHTQJpcOiu0+33oiRYyIA9kp8VwngSnKW9ezkg25cA30cnJH9InjNnz3tV7o+6A9CeqrcPcAiu1zAKjknGUL8uPhJmW3TUUI6pHs8GIkZ9kAAVbvLmkbfdjOlLTx2D02y7XzIKN+GCgLyxJPkbAetxeIYOFOFM1g8qG5csPWghc/3BI6hu4hWPI847/ZP715lsR23jDgYAlwTg1XCHSysb371G1e5otUEGpAhDUEgejiRGQ61r/eDjKlRj3jVT1taNUuYYUvKW2/+OjJObif3aKxWds+bXAtzARmjDX2GlTyDp8XqMOOicT5UwTkRarHRJeDOQYQIYuqA8mqtruW/WuaCHXYV/7o4PentspPmh9nwaucDvX+p2slRjazXgdrx2phkdjcMqEk9LYesc/UIJZydM52H2xh5+wHmi8s5wQJCoHwNiuIcqN4rjMTRGeE9KQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
      namespace: ${NAMESPACE}
