apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgALvUgxMxjOpbR84npMBSEoyac+SXNWq9Lj9gB3q++pxio2lDjia3LLDE1vGvn01QE+PSxOwTX4vCLzAx7nM/cYCInVdBL6xTzd09yfbeIkRx9oNXw4JI5EF7eqDM5Eil15YAdrFC2c3WOXMcYUb9hWj/RDOMvIqbXy6BRN34Gg6pD58xKgavbSFyq35vDtAeUOZjCIToLdgo9i13WT2Mwr/Qjni618dQz1tQs54GAIOoWE7m5ADj/VCBUcQGb3M891J+jhx1oGpfWGOxEng8cs1gCVBt81cj/NvpDwwPB+8xYz1by1JW+HmtlF4uXedu738mlt6X/9yhq3lcxzgnRCmb1yw1nf0Qj7NjbIypGtt6nyLpQTMBBl+dkiVbKadqNOJRge7JZyoJH9gNdXdbOa6rwOLsgjdxozmddd22UwdYlm0wf7cX3LN7GIYDueFBhTZuAdIL1EW11rTmTHhIW5pwfhMV1rBQy4MKjLt3N1dgaB1/JFqMfPTZVJvcK38HMdbFuuF474YCWZFSr4t+3n265Sc//jyg2fTWNMDEip7h972CJyPxZmFnuSgJBWycGyYSEvh4hS1cOeyKwr0LF7jRzdKSqDvcg0YfW4yELvKBzyHdaPBI56TR31p/XJ09pu606eZLnMjXDbKJYe03CfA9AbzkINKrJGVOOFh7P3Inn2Ztm6P/yn5VzPqvxqAFzywlSvQQZyC2jJSbYpZJAyyJSbaF8vCuuwfO+wCsyor4CXWjoJ+nHFW/4L+g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
      namespace: ${NAMESPACE}
