---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-password-pepper-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    PASSWORD_PEPPER_CURRENT: AgDN7eLr2kU72Sa9mTOyicaKydbTCuiDe+h2AvzFA9AkaAkFCVW7VU0lyx2fYpUU9rLX1vOUPac0CDMr/fN859GV2hbp+HIAvcobeeaJHYjhTuo88vjdv5a58Q2Of6kPqSh+mHh2z5PL4S0sWw9mXj4mUFjMeHkvLvV/5tVwUb6KKV7iSAYfQb0pM9Rt9mCu8jIXAKuJCsczOXvpYi00lDmE8lBVX6JHTMyPSrlExMPW0OwVTGnb6Jtu3Yx3CV30of8WXSbKQarTIZtQssnPVTGbOorJTEAHxsk892Cvawi7eewtwhmJyW+sSUaa0HCApJYfgXh9pm1hGW4uWpvJ2/aB+jwXRxeFZ3GwfJp9MyM1XiXoJ9FMJ4cISm/urKnfL9ZJ/BnD1K1KxPdJYCxxJSQU8mDk15zXp4vr9AauPnYbqgwJzSXGEQ/fyPpQ4bv3Tj9Vb1TjQoZtva6tUgif1LssV68wLc8/I3AovLGKyPii0AD+1vdAk4B+tN91dpBfKtzm24iWBYbFZGWvL5ZtSx9btJsMDir7g5fSlcF/jY88tac4QFoXpCVsD78dPcyG+FOdvXnsSanC2AcIVyJXLnvP64MCWLVe3Uew050+p2k65YBnRZfTO8Z46B+ojq8Ez1owVNVefYqhIoWmS2seTy6AlK20soBHdjjn62AGU1QgFQF0nCGW3E4LS17qw6bllFSWtBdSD9+tRw7i/8ZnDCgnDjzNnUmfsdyrGXwvPJHJIQ==
    PASSWORD_PEPPER_PREVIOUS: AgC8VIPzdMqqiLLoUdJ55m6oHXcO8SISQpORasD+Q2pU3NUMxdM3+U27x32Vfwu+bJrUGyFRVrAhpVkJv3rQr/d2e8dW5yMVon0OmHkye+Ouu9K1Z+CpzDHZVOyXEOLeBRuuO134bbFzPng7YNHs4paMfpkkNcax3lWFpuZFJudN5kA8UvGt/whm9+lC1MMrRqHkncnFjuSCiGJpQrsT/A6aki1pfiIZMoerbrNigxYrnKbQPVmJE1oVpqjHqH5kGE+54K+X9oPGD2emt/TlPDGUedzO1pzQU+y8EzVd7QCkAttLjKwigX5XnLqddRyOnGSzqhQgaIC2xNbSXgPu/jRs47YqmEh6HqI77uE7tUnYyys6NkRXeuP9M1368+Y95wgNOnPhlaQ0tUwkPQRcxBXyKx9PxWT9vuG4FSjpSs1U2CD6xm8mop+gwMtzjOhTw8py3/VYuGGmWXPJE1xsOkgKn4lKLdmHy/yn5gqyGsV6BOzXp6Exdbq5dAQYZfjRq6eukeVLHWp0waPU20cH9EN2TRrULZQ97vZBTKduHSt35FgohD6/QBKdfXtYMyef0A/B0fanpW4aX7gC6bh9Nlyyz1sffyd+xN7gTdG0nHVyHHzGLFrHA8RMW3IGmZ5vMf2yoeruui2XDXnBQc3uJ3YX/vgfq+Dn2mpMFfAKyxVm4pBdgS18WKqNtdHkWd7KTnIIrwRz1Xnk9hpFl/uikfL9IihHaqJKICyNimiPsWhLBw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-password-pepper-secret
      namespace: ${NAMESPACE}
    type: Opaque
