resources:
  - 'deployment.yml'
  - 'service-app.yml'
  - 'ingress.yml'
  # Comment-out these lines if no database is used
  - 'statefulSet.yml'
  - 'service-db.yml'
  # Add any secrets here
  - ./secrets/db.secret.yml
  - ./secrets/app.secret.yml
configurations:
  - configuration.yml


# Keep as is
namePrefix: ${BUILD_REPOSITORY_NAME}-
commonLabels:
  app: ${BUILD_REPOSITORY_NAME}
  source: ${BUILD_REPOSITORY_NAME}

commonAnnotations:
  repositoryUrl: ${BUILD_REPOSITORY_URI}

configMapGenerator:
- name: env
  envs:
  - .env