apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgA7dzbaJ6iNIQksiDnnn40lPema9UBh7qiYZP6Cz7N8aU4m5ZkWXu7vdKA6QYQGMG4dzqtW8b9Z53Vne5vxwhPNbDJ+ThifEFRM5qKBVMOjtTdTd6rmn6GlWsZMxbsAz44Z/NUFvZlV+9UviJNRlnKBQHYsD6fS0shMWpZOGQcUKpy9TeCwiSUi4o8PiI4AFMlMV6Oqkx7iaNUN7VIRZVOv+z1oj30b6GIq3o+q7KnfYzs2lb0GnSC/UwHtAgS/ES/pGj+4feRIrLLr3+3VH0u2hP7S3S4wDGIlb1M2hpjGO94EIxAOOyULw64Os/1MkYWI81/+sB8rXoWp8qCCJlZG2yMykHrru0SlxanM3opfoUllAXQyHGzOqm5is5SE9446JjMPV7+QIPy3ejPEs2VSo/V9K3xOcEG+ojDd26yWeCvRNjQ0nuOECoV/Hkwk2OIn7gFucB3+HDzCaRSFZoUiYYpzBxLG/8pKIuSf2TKTP+aTymxG1iBZeanPxxsSmXghOyF9IxBiIAmSRKTHwmxGSa3xfNttARsGd6dZbcP2e7b5qPc4PF932bCC1Zu5trZC1hVhJG4DcIqVZDuY1Zk/ZtZwjpBggTc9eyrzF3fv2wHgD60ISfzih9g9E+gToO25/KUHBY6JPMNW3bRZU+MB5FNm6U4v3RBBy0/MaYfxKfvbZO71s+WNoNo8x+s1HtbubQgyttzcDM41v0hiiIMOx9cj8/y6T3a8nk/57awoZw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
      namespace: ${NAMESPACE}

