apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgCNk/at3eimkQWX5uXibrfrM1lW1e8jzMOBQ/Pp4UZvqCYAXXHq8y6Zs7HJA92zMEC0Zuuk1Xj1947s3cHflGbt0JWPIOT/danl9pJ0RhCSBjkfKjJyJ49VYpKv5WfpBmJmOWrj4umz11dqLyVW8YKSVVm1T/n7b6Dh1GxsQmT+D7J+b38YN1dytMDg1Xjue8QDF1rdXG3xO4MqB63XEE92O0FtCcrFXUVaarsjBcPD6OmHViOHEdA/yYvZSx1mtwWSAHh4s53sj3hydYnZqvpqWkep1/cOjp8+YshehgC6mEpc1xZie+PczfOCw8FbIPEYmv/9Rv7vxF9+MN+hoKWvGuewFAIX0Km+QcZuWWdiH2cmMdM9OdYvjUyUvvDGB8PuJh+72kmxn0QnI5DaztDEQHNd7Fkg4gtC3FBEq68NGM2eK05QOQlMS5vGmEGwVO/ODxeOUoo8Kaj1jTinHLQaqK/kQleAf5DtHO0+KVMxUYhU94PW2Q88borkJUOpmP+0SvEYzRKxDz5oLJciAR0/Rd7WquufzW4zp1sMQZsFOBe83CfXTjpIX5o3nib1LyGk30fhDGjNh05jKpzh6khxPtyPN0yfaDa74E3Tp7hgQD5uGYTjP+Tlz60qBCIeoXxGGA2TnQuUSUfYwwruT0hYMOVvW4rzL7GNrivuAEFE2OCqPgwVY48MBkXCTR77udSzo5ln9ae/LXPyL9dV2vrl+g3Dq9JDu+zyXLABK1SRca67ALdOMWTykWkAAA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
      namespace: ${NAMESPACE}
