apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    APPLE_WALLET_CERTIFICATE_PASSWORD: AgDbBslYf2k37YqTfWk/4VUqY0ECFhO5e0Mlf5uwi76NqVkFClKHzaH5gpzukzTncGGzEj5AMq1jR92fWjeMkL5/ieVlVRO6HgqZkD//3M87CQQTHQi+0Or29p4ikv28qQJ5dc+uwVKjswkAYU/xylsJ9Vt/KK63PI/0qQrrvhb5QkRoeog9JiDX+/dHrtBZocPO5p138+mlb0feqWUBqSdFHXx+xAs8fTgCfuE0l/3i+Il+KqvsxRUSbgosn/NwC60iV063/4LGfhSY40rDkrpz2wJrP3UTISMUCWnWe0vh2BZyXEOcD6s1rnTtKia1eOZ1SjgFVPIJG7ysi3bckWa3tb8erDG1sU52J2ouuMlCEU0HHqlVwn06s6/QClwWpLqgUlwJwbJFvutetIjfAquuekAWZA2GoWAL+CF2tuI6YoiErX5/cDZnIkR0j+wJOsOWDt+JYV26gYvITNv/1JNx1VXbJxRFnPZE1OaNbox2hHa3g/pmQ2+SIVjhIvBWjsrPy1yhKmBuOHfW3Rbd/2xzjQPF6tHneWbuBjRIwdAvv5kxXOx9t8PC+atH6eMmBfh39xNfitexrYbDfJGTa5C/GZULqTHESyUAmFG20e5wbLOYz60joj6CEKBPqahRXykDRlEtvyIWy2NtNwZfD5K0EssGHORawm3U9MVApWOhmPLo93D1kF1zkJHRW6qBbzOgoba/puha1N2dQlqLLfVQ+8IMulzPMiE2TVPym7sS9g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-apple-wallet-password
      namespace: ${NAMESPACE}
