apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kupaliska-starz-be-minio
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgBTLNg7FCLlC9+Ukmd9EIWUr+OtcTcae1TGuS97QeKwMeDc6RhexD+5x7/hUjacOXvHwfjLeMiKXMhsBUBnku1i2h3RPl3uGswk4bcWMBTROrqOsDAw3WDkNAwlT++9ar3Ccm2LX7INVv8G+ylNtbgMFCro555b2w1jInux8/EbZO9E5aWKCUqYXWMhCDUBqV3z9CzgYsB7caWRQogKleGcD7yoKxK4iskw7x3+EUu1/OSkueUwmQLHJAWMUSyfl3vu8Aep5zWhQ4r5LDC3xjdDGo4b6YNWn26oHH/RaI3STXAgSJyHDWR4s5KbfHn65tofke9vo+FclpdUBl4x62MhOy+PbOCWxqsVJmjowFPSTiEElRBo1zfgAYic/g1/9QkYTks/yV6G8d1Ov6eN5AzE22sFu4ia79Yo71uyz9YqX20CY07jmS7UFvO4MrfUpQDoXis60IUHQiziiDDhT7+1FPl/Cu8q5q9CgttebQDciSGZ6J8WQvPMed0bHeJAAFLI6dM+aTaRR8MOt6GTHh/dW53k4EE2jF70VU9SVQgA67XMjVq+F9qS+ilQ2IRW4jv/mbrfFJuTsbLPbKHec/TwxQA3jhn+bLBRQ65oFvCMLvGFmigFedIU5DqV5Glu3Mx8nqGDeuyows1oMGBpuzvafKWYsZtT53t618dFWkmDxNW7OLVot2axXZHsHH5zrhD3cCE0Pa5dCw+wPGwZqw==
    MINIO_SECRET_KEY: AgANkypPKikbqvMfHIKPNR/wRuzBYfenzQpuZJBo6lxdLY7ZSAsta8W9KuKmP1sCbsqrhQHOgccxH6f10FkQuej8eT45F79tUMC+QDFzAn//18SpOOrSKdCRbkknaP2U5faBIJeMke+9JbMrkxQnet0Cnm+YJ7TA9bcqAoi6Sn64/sxNBywtQuJ6qn5GXcVNSF85v4Do7T5rKIJ4tmhIiCH76kzLM6Qp9LIkT5Tii6vYu2IN6dXH3i9UfJyh99pwV3lIoyP/lXsceyN9zvA3UnMCYH4emceqSzyipBeXhdro29uWlV+1eMbIZKfVM+Vy+Ai0+fOYhlJ/ciCjNqVXxeWiOY6J3Ynxls6uMhJ3Y8aXSGQTJbKPmY7o37idUTXTCc3FdrGQtzHFn750PBNG77NDFHCfZoR26lIi5gxMBiTjuon0Trg9u7SW66tifxdsYSrTzzkWytA6nVAMT/F8XPE3G5ulFkIIrH2XU4bX/hE6IBkt/v4M8PoOMXlumkpfbafSL5eT+0VZ0SdrsNmOnhbTMzvC73k97fORHF3otsjA5y1uX0cx3J2kZBBg5bvj332tc+qEH84HqoV5tyFrJalZeVNGlM+nwEinP//rz5mFEX5WMC8vpAQXUByoaIHA5u0GM05ZP2g8f80PQyKbp1nC4CGtGhRLr1LlmSKAx+6nhpir8D/HBgEH4kB8YEUabUALtWIqU99JXhLRB2xp0QUdyEGH1BwVoz2UPG6MYyrzg3cpMpcONNzojPAFNteHVb5jl66lRMsnVQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: kupaliska-starz-be-minio
      namespace: ${NAMESPACE}

