---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-password-pepper-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    PASSWORD_PEPPER_CURRENT: AgAnRjpUUTD8YwmfefPsubRAfOIFBj9n7px+HDxfqAJn5x7bEc3H1xxcyScqnwUFrBFWmGbho9h5wV6lwNv6W5Oe9/uKzWF88EIVs7Jmxsv47D69OYr9RKG2D32vQyn8JvwO6EYp13GdLimt8oT4IgM4tCnSRLNzA6v9icFl8cZhzWVDC2U6sfAR1ioZ5T7rlTz9nNpL/0fA95mXmTpPodRocaas7Kogcx0sUFAThRlFcYhdL+07YmrOW2WDskzxDyxqNhgsByd3YgC2ALVw+ZxghNrUITv25212grRTkLoxJ78waod/1TQyYbPf67Vr+p4SWvzGArL5IF5Gu2ZP9O+CP3+FV77DHGlWAYtD/EvpQyXq6DurZPCHyX8/K8cmatZLlRDktrgeNqTae1aHUvkzt1he2/VwCatj5QhxWHiSPqtNZ86JGaqwfMYmM50H+XiiRXzMPugXVEur1mTAY53bYKwDCnXdaIWbf2IqwhGs5yC8BdycmTLSwtlmfetcMKlIvqTYzNs3Q0F4LPaO/noL71bZAnDLNacRjmeFglAqZ7qdNV2lwSOhREIcPVn2fe7JjbBE+CrpaVsf4S/haz6K6azCRPUUZqdnz3qtPQPAHi2qhbPQrc7g94FKTNDuUxg69sBQRChQJqXT6g2brqIK5rvuVad2HjZyX8h5AAbz/H69DAnKwli3GMeN6pn4vc+hgQQyi9TXtsqoooibeH3QQ7DFs97tRuviVi1UWYbZSw==
    PASSWORD_PEPPER_PREVIOUS: AgAK4EavKFmo88Krp2EuPL5eS95ouTB0Eon9qhE68gLknbpbvsxTQzs4de8vXqNYUKphpXY/prHrGEOKWZsCBqzMpx1KgrHViitOLWaP9JvxA5ltbxPRhzwK56hUnwplucVf81Vbu5vbwq/yPqy2sicJM4L9PR2+44DpzihN8vhVel7h5MjyVeEa3yicxptsGfk/pTpgkI3zn5bbFvDP0TsunEakSJKGx3YN05jcCJ/gP84jkRSbH0CPW1k9ymvf5Z33ImMsWVAAz+FsrnxdxFNzsN3ZcpXZWBvldDJIQWlk7L/r53JkePAiTCm21hE7Lf/eT6GuSmqt2H/qKOMxauBJjE5fBYlczepHspTeuaDPwTrsYYUkorJA7AYQI8d+iSxJf4M7NamndQ3jAveSSEUv1t3nC2/MutNvwyD/j43UdOZY2TARZqMhWSeZ7/RNDbRfrsFT0FSfR4CI9PfN2nQePHR6aljWPJnOnSgrT7gFySXC7y1685PLnk6xi+UzPeeqD1K/kkU73++sfUDfeAQ1Yqsz85nWJcaw+6RKK2+WNQcdr510RaQAA2YxoMZDkjnhV0wXE+/a2d2N9cxRrl/3+RgTaycdOdXYh6VpWAjNe7U/0MtXhhaa2xVb8ndpaCySEVAlfnaOl/vJdtIhUZIQvuQg3S+YEfJsVQF4kjjUClRJ9VOkQDhOq4M5fw3GcT2YDqF/MmzMINiZ2IN7NCkkbpnOhrYk4c3EHoifJgqyCA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-password-pepper-secret
      namespace: ${NAMESPACE}
